name: Test Build (single patch)

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build patches.mpp
    if: |
      github.event_name == 'workflow_dispatch' ||
      startsWith(github.event.head_commit.message, 'sin:')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle (with caching)
        uses: gradle/actions/setup-gradle@v6

      - name: Build patches.mpp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :patches:buildAndroid

      - name: Upload patches.mpp
        uses: actions/upload-artifact@v4
        with:
          name: patches-mpp
          path: patches/build/libs/patches-*.mpp
          retention-days: 3
